version: '2'

services: 

 Apache:
  build: ./Apache/.
  image: apache:latest
  depends_on:
   - MySQL
  links:
   - MySQL
  ports:
   - 8080:80
  environment:
   TWINBLAST_DB_HOST: MySQL:3306
   TWINBLAST_DB_PASSWORD: twinblast

 MySQL:
  image: mysql
  volumes:
   - "./.data/db:/var/lib/mysql"
  restart: always
  environment:
   MYSQL_ALLOW_EMPTY_PASSWORD: 1
   MYSQL_DATABASE: twinblast
   MYSQL_USER: twinblast
   MYSQL_PASSWORD: twinblast
  expose: 
   - "3306"
