version: '2'

services: 

 LGTview:
  build: ./LGTview/.
  image: lgtview:latest
  depends_on:
   - MySQL
   - mongo
  ports:
   - 8080:80
  environment:
   TWINBLAST_DB_HOST: MySQL:3306
   TWINBLAST_DB_PASSWORD: twinblast

 MySQL:
  image: mysql
  volumes:
   - "./.data/db:/var/lib/mysql"
  restart: always
  environment:
   MYSQL_ALLOW_EMPTY_PASSWORD: 1
   MYSQL_DATABASE: twinblast
   MYSQL_USER: twinblast
   MYSQL_PASSWORD: twinblast
  expose: 
   - "3306"

 mongodata:
  image: mongo:2.6
  volumes:
   - /data/db
  command: --break-mongo

 mongo:
  image: mongo:2.6
  volumes_from:
   - mongodata
  ports:
   - "27017:27017"
  command: --smallfiles --rest --auth
